services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:master
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    restart: always