services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:master
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:master
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:master
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:1.0.0
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
services:
  postgres:
    image: postgres
    restart: always
  redis:
    image: eqalpha/keydb
    restart: always

  api:
    image: ghcr.io/itchatapp/api:master
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    restart: always
